name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push builder
      uses: docker/build-push-action@v2
      with:
        context:  builder/.
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
          jonasbg/helm:alpine 
          jonasbg/helm:latest
    - name: Build and push yq
      uses: docker/build-push-action@v2
      with:
        context:  yq/.
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
          jonasbg/yq:alpine
          jonasbg/yq:latest
